### ISSUE TITLE
Configuration / Initializing advice

### ISSUE THREAD

**Issue by Leref** [Faf4a/dashboard#19]
I would believe it's more ethical to have a drag-in drop based system by saving each assignment, instead of having to manually input what is in each category etc.
For example 

```js
navbar: [ // Custom Navbar
    { title: "Dashboard", to: "/dash" },
    { title: "Commands", to: "/commands" },
    { title: "Status", to: "/status" },
    { title: "Invite", to: "/invite" },
    { title: "Discord", href: "https://example.com" },
  ],
  ```
  
  All of this can be changed into a UI complex of having an editor built-in which allows to assign/not assign in the actual navbar.

**Comment by Faf4a** [comment]
after finishing the core, maybe
